### PR TITLE
Tomas dev

### PR DESCRIPTION
**Pull request by webDesignMumeishon**

### CODE REVIEW

**Comment by demiculus** [comment]
@webDesignMumeishon can you go back to the readme, read it, and apply it? 

You need to be able to apply instructions of that read me clearly.

**Comment by demiculus** [comment]
Hey @webDesignMumeishon 

Nice work, can you do some edits?
Create a new PR merging to the main branch and tag me for review.

At the new branch, I want to see a couple of things

1. Communication: learn to write better PR descriptions. You can google how to.
2. Clean commits: Commits are too big, confusing, etc. Google `best commit practices` and apply them in your workflow. In your PR description, include which ones you applied and any detail you feel would add value.
3. Clean code: Your code works but it is not clean. Google `clean code best practices & principles` and apply some of them. In your PR description, include which ones you applied and any detail you feel would add value.
4. Modularity: Your code can be more modular, feel free to google `best javascript modularity practices` and apply a few of them. In your PR description, include which ones you applied and any detail you feel would add value.
5. Bug: The ball, paddle & sides go in each other. They shouldn't overlap.
6. Fun mechanic: The game isn't fun. Add any mechanic that you think would make the game more fun.
7. Make sure the PR description links to this comment

Note that I'm looking to see if you can 
- google
- learn
- apply the right way

I'm expecting you to learn a lot of principles, not just a few. So don't hold yourself back. Even if you don't get in this will increase your skills.

Let me know if there are any questions.

Some google queries to help you out
`how to X`
`best X practices`
`best X principles`
Replace X with whatever is needed
- writing modular javascript code
- PR descriptions
- Commit naming conventions
- clean code javascript
- git PR tutorials
etc.

**Comment by webDesignMumeishon** [comment]
Hey Demi! 
How are you today !?
Thank you so much for the opportunity and the incredible feedback
I wasn’t expecting to be evaluated yet ! I was going to add a new pull request. I got confused a little bit in the assignment.
Now I will put my hands to work and try to apply everything you have mentioned!

Thank you so much for your time Demi!

**Comment by webDesignMumeishon** [comment]
Sorry again Demi

I didn't quite understand what you meant with

   1. Bug: The ball, paddle & sides go in each other. They shouldn't
   overlap.

If you can provide me with more insight about it would be great!

Thank you so much!

**Comment by webDesignMumeishon** [comment]
Sorry again!
When you talk about Modules, do you mean using a tool like webpack for
modularizing my JS code?

**Comment by demiculus** [comment]
> . Bug: The ball, paddle & sides go in each other. They shouldn't
   overlap.

Ball is going inside objects 
image

> When you talk about Modules, do you mean using a tool like webpack for
modularizing my JS code?

No code modularity. https://medium.com/@fahdmekky/writing-clean-and-modular-code-eb1eb8bba87f

Google how to write modular code

**Pull request merged**
